### ISSUE TITLE
main panic with index out of bounds

### ISSUE THREAD

**Issue by Herbert-Karl** [mkubasz/duck_rs#2]
Execution currently failes for me in following function at line 204:
https://github.com/mkubasz/duck_rs/blob/77bafcf43deb83311a700f3377c014061c718f6f/duck_main/src/dataframe.rs#L201-L207

Thrown error is:
> thread 'main' panicked at 'index out of bounds: the len is 6 but the index is 6'

this error doesnt appear, if i switch 'col' and 'row' for indexing the Array.
But i dont know yet, why this is that way.

**Comment by mkubasz** [comment]
Fixed in a new commit.
